### ISSUE TITLE
How to pass model do_sketching parameter? 

### ISSUE THREAD

**Issue by alfredcs** [dhroth/sketchedsgd#1]
Ran into the following error and please advise when free. Thanks!

    summer = SketchedSum(optimizer, c=20, r=5, numWorkers=int(self.args.num_users))
   ......
    if p.do_sketching:
   ......
AttributeError: 'Parameter' object has no attribute 'do_sketching'

**Comment by BelhalK** [comment]
I suppose you need to replace `do_sketching` by `doSketching`
Let me know if that works out.

**Comment by dhroth** [comment]
sorry I missed this earlier. Are you wrapping your model with `SketchedModel()`, as on line 11 of example.py? Doing so sets do_sketching on each of the model parameters, which `SketchedSum.__init__()` later expects.

**Comment by dhroth** [comment]
Closing for now since it's been a couple weeks. Feel free to re-open if my comment doesn't address the error you're getting
